### ISSUE TITLE
Trouble installing plugins

### ISSUE THREAD

**Issue by Mailaender** [vogellacompany/com.vogella.vde#69]
```
An error occurred while installing the items
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]org.eclipse.rcp.configuration_root.gtk.linux.x86 1.0.0.v20140120-0614, action=org.eclipse.equinox.internal.p2.touchpoint.natives.actions.ChmodAction).
The action chmod failed - file /opt/voclipse/eclipse does not exist
```

`sudo mkdir -p /opt/voclipse/eclipse` resolved it which is probably strange as it should install into `~/.eclipse`. Also the update sites stay empty not giving me a chance to install something new:

![update-sites](https://f.cloud.github.com/assets/756669/2098976/eab5f07e-8f35-11e3-8805-15b9b2a1d6da.png)

**Comment by vogella** [comment]
Are you using "your" packaged version or a simple download of voclipse? I suggest to validate that errors also happen with the "normal" package. In this case I assume something is wrong with your package or its rights to right to the filesystem.

**Comment by Mailaender** [comment]
Hmm, the log is a little crowded https://gist.github.com/Mailaender/8853348 I am not really sure what to make out of the file does not exist messages (checked some, they are really missing, not just not readable). "failed on Keine Route zum Zielrechner. Retry attempt 0 started" could be wrong proxy settings when switching networks. Need to reproduce this better.

**Comment by Mailaender** [comment]
Wait, this is actually a GUI bug:

![empty-plugins-selector](https://f.cloud.github.com/assets/756669/2104392/ee07b560-8f7a-11e3-8ac8-9eb172db291b.png)

selection lists are invisible however I can click them and the white window changes.

**Comment by vogella** [comment]
Are you sure you use GTK2? This looks like https://bugs.eclipse.org/bugs/show_bug.cgi?id=424343

**Comment by Mailaender** [comment]
`export SWT_GTK3=0 & voclipse` fixes the list view problem. It also exposes the crash when trying to install new software in the terminal output:

```
java.net.UnknownHostException: mPad-X230: mPad-X230: Der Name oder der Dienst ist nicht bekannt
        at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
        at ch.ethz.iks.slp.impl.SLPCore.<clinit>(SLPCore.java:176)
        at ch.ethz.iks.slp.impl.OSGiPlatformAbstraction.logDebug(OSGiPlatformAbstraction.java:101)
        at ch.ethz.iks.slp.impl.OSGiPlatformAbstraction.<init>(OSGiPlatformAbstraction.java:71)
        at ch.ethz.iks.slp.impl.Activator.start(Activator.java:37)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:928)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:317)
        at org.eclipse.osgi.container.Module.doStart(Module.java:558)
        at org.eclipse.osgi.container.Module.start(Module.java:429)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:531)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:330)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:306)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:374)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:331)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:323)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2493)
        at java.lang.Class.getConstructor0(Class.java:2803)
        at java.lang.Class.newInstance(Class.java:345)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:755)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:706)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:928)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:317)
        at org.eclipse.osgi.container.Module.doStart(Module.java:558)
        at org.eclipse.osgi.container.Module.start(Module.java:429)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:531)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:330)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:306)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:374)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:331)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:323)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:566)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
        at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
        at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
        at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
        at org.eclipse.ecf.internal.core.identity.Activator.addNamespaceExtensions(Activator.java:236)
        at org.eclipse.ecf.internal.core.identity.Activator.setupNamespaceExtensionPoint(Activator.java:281)
        at org.eclipse.ecf.core.identity.IDFactory.initialize(IDFactory.java:46)
        at org.eclipse.ecf.core.identity.IDFactory.getNamespaceByName(IDFactory.java:145)
        at org.eclipse.ecf.provider.filetransfer.retrieve.MultiProtocolRetrieveAdapter.getRetrieveNamespace(MultiProtocolRetrieveAdapter.java:49)
        at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.sendRetrieveRequest(FileReader.java:418)
        at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.readInto(FileReader.java:355)
        at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:101)
        at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:156)
        at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadIndexFile(AbstractRepositoryManager.java:735)
        at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:657)
        at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
        at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
        at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:117)
        at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:102)
        at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$2.runModal(PreloadingRepositoryHandler.java:83)
        at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: java.net.UnknownHostException: mPad-X230: Der Name oder der Dienst ist nicht bekannt
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
        ... 66 more
```

**Comment by vogella** [comment]
Where does mPad-X230 come from? I never saw this message.

2014-02-07 13:04 GMT+01:00 Matthias Mailänder notifications@github.com:

**Comment by Mailaender** [comment]
It is the name of my localhost. Also I don't have IPv6 support at home, work and mobile yet.

**Comment by Mailaender** [comment]
This is fixed in the latest RPM/voclipse build https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.voclipse.packaging/36/

**Comment by Mailaender** [comment]
![voclipse](https://f.cloud.github.com/assets/756669/2229982/054f4402-9af9-11e3-8c98-ce08c35b6ba3.png)
